### ISSUE TITLE
Create a Readme file with errors to fix?

### ISSUE THREAD

**Issue by suchov** [Kottans/mock-repo#1]

**Comment by AMashoshyna** [comment]
ok, 10 minutes

**Comment by suchov** [comment]
))) No rush

**Comment by suchov** [comment]
creating Issues - it's one of the way's of story creation too ;)

**Comment by AMashoshyna** [comment]
Hi,

this is a training repository for [Kottans web course](https://github.com/Kottans/web). You can try sending pull-requests to this repoistory proposing a change..
The change can be anytthing you like - for example, fixing a typo in README.md. Consider this phrase, for example: 


*intntionally misspeled phrase*


Try it! It’s fun, we promise :)

By the way, creating issues is fun too!

**NB! You pull-request may not be reviewed very quickly, please have patience.**

**Comment by AMashoshyna** [comment]
@suchov please add README, I can't fork an empty repo
