### ISSUE TITLE
Remove enrollees' additions from 2017

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/mock-repo#143]
`README.md` becomes heavy.
It seems reasonable to take enrollees' additions from 2017 away.

**Scenario 1**
One option is to move postings to a dedicated file. However, the repo itself remains heavy due to images.

**Scenario 2**
So the other option is to:
1. Choose a 'break point' i.e. one of commits from early 2018 (e.g. 2d69ab0 dated February 25, 2018)
1. Tag the 'break point' commit as `v.2017-2018` (similar to how it's done in [kottans/frontend](https://github.com/kottans/frontend/tree/v.2017-2018))
1. Remove all additions till the 'break point' including associated images (definitely need to set up a dedicated directory for new images in 2019)

@suchov @zonzujiro @AMashoshyna what do you think?

**Comment by zonzujiro** [comment]
All 3 options is ok for me. All these gifs are useless 🤷‍♂️

**Comment by suchov** [comment]
🤷‍♂️

**Comment by AMashoshyna** [comment]
I like option 3.

**Comment by OleksiyRudenko** [comment]
Got no enough powers in this repo.

Can please someone properly authorized navigate to the [create a new release page](https://github.com/kottans/mock-repo/releases/new) and add tag `v.2017-2018` at commit 2d69ab0 ?

Thanks!

@suchov @zonzujiro @AMashoshyna

**Comment by OleksiyRudenko** [comment]
Also tagged an above mentioned commit: [kottans/mock-repo/tree/v.2017-2018](https://github.com/kottans/mock-repo/tree/v.2017-2018)
