### ISSUE TITLE
Hello from new students

### ISSUE THREAD

**Issue by rpiasetska** [kottans/mock-repo#471]
## Hi Guys! 
I'm Ruslana. I don't have cat but I dream to have it & frontend job in near future =)))
### Good luck & hugs!
![Screenshot 2020-10-19 at 22 09 29](https://user-images.githubusercontent.com/47031282/96500594-cb779a80-1257-11eb-9689-79983121b6c3.png)

**Comment by nazmariam** [comment]
Hi! Very nice! 
This is issue, did you make PR to README.md?

**Comment by rpiasetska** [comment]
Oh... I'm sorry. I wrote in the wrong place... 
I just have made PR. Thanks for assist
